name: TSETMC Screenshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */1 * *'  ## at 09:00 on every day-of-month (being 12:30 for our timezone)

jobs:
  tsetmc-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Taking screenshot
        uses: ./.github/actions/capture-website-cli
        with:
          url: 'http://www.tsetmc.com'
          name: 'tsetmc_screenshot.jpg'
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
